version: '3.7'

services:
  api:
    image: cyberduck/php-fpm-laravel:8.0
    env_file: .env
    working_dir: /app
    volumes:
      - ./api:/app

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./client:/app
      - ./docker-compose/nginx/chat-nginx.conf:/etc/nginx/conf.d/default.conf

  client:
    image: node:16-alpine
    volumes:
      - ./client:/app
    working_dir: /app
    command: npm run start

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - "mysqldata:/var/lib/mysql/"
    ports:
      - 3306:3306

volumes:
  mysqldata:

networks:
  default:
