version: '3.7'

services:
  api:
    image: cyberduck/php-fpm-laravel:8.0
    env_file: .env
    working_dir: /app
    volumes:
      - ./api:/app
    depends_on:
      - redis

  echo:
    image: node:16-alpine
    env_file: .env
    working_dir: /app
    volumes:
      - ./api/:/app
    command: >
      sh -c "npm install &&
      npm install -g laravel-echo-server &&
      laravel-echo-server start --force"
    ports:
      - 6001:6001
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./client:/app
      - ./docker-compose/nginx/chat-nginx.conf:/etc/nginx/conf.d/default.conf

  client:
    image: node:16-alpine
    volumes:
      - ./client:/app
    working_dir: /app
    command: npm run start

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - "mysqldata:/var/lib/mysql/"
    ports:
      - 3306:3306

  redis:
    image: redis:6.0
    ports:
      - "6379:6379"

volumes:
  mysqldata:

networks:
  default:
